### ISSUE TITLE
IMS LTI Support

### ISSUE THREAD

**Issue by abertranb** [atomicjolt/OpenAssessmentsClient#453]
Hi! first of all thanks for this awesome project, I have a question

In Readme.md specify the IMS LTI information but I can't found how launch and configure it

Thanls!

**Comment by jbasdf** [comment]
Hi. Open Assessments is just a client side application. You'll have to build out the LTI launch bit. We have a starter app that can help with that - https://github.com/atomicjolt/lti_starter_app

**Comment by abertranb** [comment]
Thanks, we will review It!
